// Généré depuis host/certs/ca.crt : certificat PUBLIC de notre autorité (pas un secret).
// Sert d'ancre de confiance TLS : l'ESP n'accepte que le broker signé par notre CA.
#pragma once
static const char CA_CERT[] PROGMEM = R"PEM(
-----BEGIN CERTIFICATE-----
MIIBzDCCAXKgAwIBAgIUeknGSKQ86qrew4Kc5PpitU17bEowCgYIKoZIzj0EAwIw
MjETMBEGA1UECgwKU2VudGluZWwtWDEbMBkGA1UEAwwSU2VudGluZWwtWCBSb290
IENBMB4XDTI2MTAwNTE0NDIwNFoXDTI5MTAwNDE0NDIwNFowMjETMBEGA1UECgwK
U2VudGluZWwtWDEbMBkGA1UEAwwSU2VudGluZWwtWCBSb290IENBMFkwEwYHKoZI
zj0CAQYIKoZIzj0DAQcDQgAE50JytyyjI8xgyWOTpX2zkbPbhJF5aO0sw+bk88Cb
jps0ip3ZCX1NGafZuTfvwY29AGUOXVRw04LTCM7lGwcDuqNmMGQwHwYDVR0jBBgw
FoAUBolnFT2+vyP5xEvDRT5AgYIOguEwEgYDVR0TAQH/BAgwBgEB/wIBADAOBgNV
HQ8BAf8EBAMCAQYwHQYDVR0OBBYEFAaJZxU9vr8j+cRLw0U+QIGCDoLhMAoGCCqG
SM49BAMCA0gAMEUCIGkxzhxotsVMA9LUUbGRrjs7NfUfwt8ogFiJWpX5KRXUAiEA
q3+iIZrJ6Q/pxNqDC1eEb/YVsNYIFpTYMwrpOJIW+9o=
-----END CERTIFICATE-----
)PEM";
