; Sentinel-X — firmware ESP8266 (NodeMCU Lolin v3, ESP-12E)
; Compiler : pio run        Téléverser : pio run -t upload        Moniteur : pio device monitor

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 460800
monitor_filters = esp8266_exception_decoder
lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.2
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/Adafruit SSD1306 @ ^2.5.13
    adafruit/Adafruit GFX Library @ ^1.12.0
